language: ruby
rvm:
  - jruby
  - 2.2.8
  - 2.3.5
  - 2.4.2

env:
  global:
    - JRUBY_OPTS="--2.0"

gemfile:
  - Gemfile
  - gemfiles/active_record-rails40.gemfile
  - gemfiles/active_record-rails41.gemfile
  - gemfiles/active_record-rails42.gemfile

before_script:
  - mysql -e 'create database sorcery_test;'

before_install:
  - rvm get stable --auto-dotfiles
  - gem update bundler

matrix:
  allow_failures:
    - rvm: jruby

  exclude:
    - rvm: 2.2.8
      gemfile: gemfiles/active_record-rails40.gemfile

    - rvm: 2.3.5
      gemfile: gemfiles/active_record-rails40.gemfile

    - rvm: 2.4.2
      gemfile: gemfiles/active_record-rails40.gemfile

    - rvm: 2.4.2
      gemfile: gemfiles/active_record-rails41.gemfile

    - rvm: 2.4.2
      gemfile: gemfiles/active_record-rails42.gemfile

    - rvm: jruby
      gemfile: Gemfile
